name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    defaults:
        run:
          shell: powershell
  
    steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '^3.7.0'
            channel: stable
  
        - name: Flutter doctor
          run: flutter doctor
  
        - name: Get dependencies
          run: flutter pub get
  
        - name: Format code
          run: flutter format --set-exit-if-changed .
  
        - name: Analyze
          run: flutter analyze
  
        - name: Run tests
          run: flutter test
  
        - name: Build APK (optional)
          run: flutter build apk --debug
