name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              flutter-version: "^3.7.0" # Update if needed
    
          - name: Install dependencies
            run: flutter pub get
    
          - name: Analyze code
            run: flutter analyze
    
          - name: Run tests
            run: flutter test
    
          - name: Build APK
            run: flutter build apk --release
    
          - name: Install yq
            shell: cmd
            run: choco install yq
